### PR TITLE
Updated monolog version

### PR DESCRIPTION
**Pull request by fiboknacky**

### CODE REVIEW

**Comment by emilianotisato** [comment]
Yes please, update monolog library. Merge this PR

**Comment by petebowen** [comment]
Hi. Please can you trigger an update on Packagist for this as it's still showing the dependency as "monolog/monolog: ^1.17.1". Thanks

**Comment by fiboknacky** [comment]
Done. Sorry for inconvenience.

**Comment by whiteDigitalAI** [comment]
Packagist still showing it's still showing the dependency as "monolog/monolog: ^1.17.1". conflict. Kindly fix

**Comment by whiteDigitalAI** [comment]
Problem 1
   - The requested package monolog/monolog (locked at 2.1.1, required as ^1.7)
s satisfiable by monolog/monolog[2.1.1] but these conflict with your requiremen
s or minimum-stability.
 Problem 2
   - Installation request for monolog/monolog ^1.7 -> satisfiable by monolog/mo
olog[1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.13.1, 1.14.0, 1.15.0, 1.16.0, 1.17.0, 1.
7.1, 1.17.2, 1.18.0, 1.18.1, 1.18.2, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.22.1, 1.
3.0, 1.24.0, 1.25.0, 1.25.1, 1.25.2, 1.25.3, 1.25.4, 1.25.5, 1.7.0, 1.8.0, 1.9.
, 1.9.1, 1.x-dev].
   - facade/ignition 2.3.7 requires monolog/monolog ^2.0 -> satisfiable by mono
og/monolog[2.x-dev].
   - facade/ignition 2.3.7 requires monolog/monolog ^2.0 -> satisfiable by mono
og/monolog[2.x-dev].
   - facade/ignition 2.3.7 requires monolog/monolog ^2.0 -> satisfiable by mono
og/monolog[2.x-dev].
   - Conclusion: don't install monolog/monolog 2.x-dev
   - Installation request for facade/ignition (locked at 2.3.7, required as ^2.
.6) -> satisfiable by facade/ignition[2.3.7].

**Comment by thangduo** [comment]
@whiteDigitalAI how do you get these problems? Are you using a diagnostic tool?

**Pull request merged**
