### PR TITLE
possibility to set custom curl options

### PR DESCRIPTION
**Pull request by gitazem**
` sometimes need to set some useful curl options. example:`

 **`$customCurlOptions =  ['CURLOPT_TIMEOUT' => 1];`**

### CODE REVIEW

**Comment by gitazem** [comment]
I signed it!

**Comment by fiboknacky** [comment]
Hi @gitazem 

Thanks so much for your pull request.
Could you please clarify in what situations you would like to set extra cURL options for downloading reports?

Best,
Knack

**Comment by gitazem** [comment]
Hello,

I am downloading many reports each day, and sometimes wsdl called via curl takes too long to respond. When i will set a smaller timeout, i can retry request faster. So all my download runs faster. Thank you !

Best,
Gita

**Comment by fiboknacky** [comment]
Hello Gita,

But AdWords API reporting isn't involved with WSDL and SOAP calls, I believe.
So you benefit from this curl options for normal HTTP requests?

Best,
Knack

**Comment by gitazem** [comment]
Hello, 

yes, sorry, you are right. Its for normal HTTP requests. 

Best,
Gita

**Comment by hakimio** [comment]
@fiboknacky Can we also have this in experimental branch?

**Comment by fiboknacky** [comment]
Hi @hakimio,

In the experimental branch, we use [Guzzle](http://docs.guzzlephp.org/en/latest/) for downloading reports.
You can set your custom cURL options by following [this section](http://docs.guzzlephp.org/en/latest/faq.html#how-can-i-add-custom-curl-options).

Best,
Knack

**Comment by hakimio** [comment]
@fiboknacky 
Are you suggesting that I make a pull request with changes for experimental branch like Gita did for master? Or is there already a simple way to get guzzle client instance and set cURL options? I just want to set timeout options like Gita did before calling downloadReport().

**Comment by fiboknacky** [comment]
Hi @hakimio,

I think the support for setting custom cURL options is already supported via construction of `Client` object.

More specifically, you can create a Guzzle `Client` by passing an array containing your [curl options](http://docs.guzzlephp.org/en/latest/faq.html#how-can-i-add-custom-curl-options) as its [first parameter](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L62).

Then, you specify this object as a parameter of [ReportDownloader](https://github.com/googleads/googleads-php-lib/blob/experimental/src/Google/AdsApi/AdWords/Reporting/v201607/ReportDownloader.php#L60).
Based on the documentation of Guzzle and from [its code](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L62), this should work.
Please let me know if it doesn't.

So, probably we don't need to modify our code in the experimental branch.

Cheers,
Knack

**Comment by fiboknacky** [comment]
Hi @hakimio,

That is another possible way to do.
But Guzzle opens room for many more configurations, not only request options.
For instance, you can inject the [middleware and handlers](http://docs.guzzlephp.org/en/latest/handlers-and-middleware.html) via this `Client` already.

Curl options are another kind of configs that can be treated in the same way--passing as parameter to `Client` constructor, so I don't see the point why we want to bloat the signature of `ReportDownloader` by creating another parameter (which can be combined into the `Client` object itself) and then merge those configs with AdWords API default options by ourselves (which is actually handled by Guzzle for [every request](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L234)).

Best,
Knack

**Comment by hakimio** [comment]
I see. Thanks for explanation.

**Pull request merged**
