### PR TITLE
Fix bug with fromString param and handle errors from parse ini functions

### PR DESCRIPTION
**Pull request by shakaran**
This PR basically is a small fix for fromString() which never process the right string (it seems a typo in the var for passing the data) and add a extra checking for files INI that could break the configuration loading throwing a exception if invalid errors were found.

### CODE REVIEW

**Comment by shakaran** [comment]
I signed it!

**Comment by shakaran** [comment]
I also add the fromString function for OAuth2TokenBuilder class. It could be interesting add the fromString function in the interface AdsBuilder so other classes inheriting from AdsBuilder will have to implement this function

**Comment by shakaran** [comment]
@vtsao when will go this fix merged to experimental? 3 weeks and I don't see any progress just for merge this pull request

**Comment by vtsao** [comment]
Fixed in the latest version of experimental:
https://github.com/googleads/googleads-php-lib/tree/experimental

**Pull request closed without merging**
