### PR TITLE
use semver for dependencies

### PR DESCRIPTION
**Pull request by mikemeier**
I struggled to install this package with symfony 2.8, so I tried to figure out which versions are really needed and adapted the dependencies to follow http://semver.org schema.

### CODE REVIEW

**Comment by fiboknacky** [comment]
Hello Mike,

Could you please clarify a bit more why you propose this change?
What happened when you run `composer require googleads/googleads-php-lib:dev-experimental`? 
From what I tested, it downloaded Symfony for me without problems.

Best,
Knack

**Comment by mikemeier** [comment]
@shakaran Dependency is added, sorry for that. Was working on an old fork.
@fiboknacky I get this composer error: 

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install symfony/symfony v2.8.11
    - Conclusion: don't install symfony/symfony v2.8.10
    - Conclusion: remove symfony/symfony v2.8.9
    - Conclusion: don't install symfony/symfony v2.8.9
    - Conclusion: don't install symfony/symfony v2.8.8
    - Conclusion: don't install symfony/symfony v2.8.7
    - Conclusion: don't install symfony/symfony v2.8.6
    - Conclusion: don't install symfony/symfony v2.8.5
    - Conclusion: don't install symfony/symfony v2.8.4
    - Conclusion: don't install symfony/symfony v2.8.3
    - Conclusion: don't install symfony/symfony v2.8.2
    - Conclusion: don't install symfony/symfony v2.8.1
    - googleads/googleads-php-lib dev-experimental requires symfony/serializer ~3.0.3 -> satisfiable by symfony/serializer[v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9].
    - googleads/googleads-php-lib dev-experimental requires symfony/serializer ~3.0.3 -> satisfiable by symfony/serializer[v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9].
    - don't install symfony/serializer v3.0.3|don't install symfony/symfony v2.8.0
    - don't install symfony/serializer v3.0.4|don't install symfony/symfony v2.8.0
    - don't install symfony/serializer v3.0.5|don't install symfony/symfony v2.8.0
    - don't install symfony/serializer v3.0.6|don't install symfony/symfony v2.8.0
    - don't install symfony/serializer v3.0.7|don't install symfony/symfony v2.8.0
    - don't install symfony/serializer v3.0.8|don't install symfony/symfony v2.8.0
    - don't install symfony/serializer v3.0.9|don't install symfony/symfony v2.8.0
    - Installation request for symfony/symfony 2.8.* -> satisfiable by symfony/symfony[v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - Installation request for googleads/googleads-php-lib dev-experimental -> satisfiable by googleads/googleads-php-lib[dev-experimental].
```

**Comment by fiboknacky** [comment]
Hello Mike,

What does your `composer.josn` look like?
Do you have a line that requires `symfony/serializer` too?

Best,
Knack

**Comment by mikemeier** [comment]
I require `"jms/serializer": "^1.1"`

**Comment by fiboknacky** [comment]
Hello Mike,

First, it looks like the conflict on your `composer.json`, which I doubt if it's related to `jms` or not, as it doesn't require `symfony/serializer` based on [packagist](https://packagist.org/packages/jms/serializer#1.1.0).
Next, the conflict message you've given is not about `symfony/serializer` but about `symfony/symfony`.

Do you request `symfony/symfony` as well?
It seems your issue is similar to [this](http://stackoverflow.com/questions/16672993/composer-json-fails-to-resolve-installable-set-of-package) and [this](http://stackoverflow.com/questions/21054223/how-to-resolve-laravel-version-conflicts-between-4-1-installation-and-4-0-depend).

Our code is developed using Symfony's serializer v3.0.3.
There might be some chages in design and classes between v2.8.0 and v3.0.3 that would affect our code, so I don't think we can just expand the requirement to previous versions.

Best,
Knack

**Comment by fiboknacky** [comment]
Hello Mike,

As mentioned in my previous reply, it's still not clear how your commit resolve the issue you've mentioned, we can't accept this pull request yet.
In addition, it would be great if you could submit pull request that makes a change on one topic. 
Currently, it seems `AdWordsSessionBuilder` is also modified in your pull request as well.

I'll close this issue for now, as there are no replies for a long time. 
Please feel free to open it if you still have doubts/questions on this.

Cheers,
Knack

**Pull request closed without merging**
