### PR TITLE
Assign env values to variables

### PR DESCRIPTION
**Pull request by dionbosschieter**
Throws PHP Fatal error because you can't use a function return value in write context
EnvironmentalVariables.php:37: Can't use function return value in write context

### CODE REVIEW

**Comment by dionbosschieter** [comment]
I signed it!

**Comment by fiboknacky** [comment]
What PHP versions are you using?
It shouldn't show that error message if the PHP version is >= 5.5 based on the [ref page](http://php.net/manual/en/function.empty.php).

**Comment by dionbosschieter** [comment]
php 7.1

**Comment by fiboknacky** [comment]
It looks like this is not necessary anymore.
Thanks for your contribution anyway. :)

**Pull request closed without merging**
