### PR TITLE
Add Symfony 5 support

### PR DESCRIPTION
**Pull request by k0d3r1s**
Add Symfony 5 support

#SymfonyHackday

### CODE REVIEW

**Comment by fiboknacky** [comment]
@k0d3r1s 

I found PHPUnit fails with Symfony 5.0.
Could you also address the failed tests first and attach the results here?

**Comment by k0d3r1s** [comment]
will take a look when have free time

**Comment by fiboknacky** [comment]
> will take a look when have free time
@k0d3r1s 
Any updates?

**Comment by k0d3r1s** [comment]
unfortunetly not. there is something with the way this lib uses symfony library but I haven't got to actually debugging / fixing this issue

**Comment by fiboknacky** [comment]
This is merged in https://github.com/googleads/googleads-php-lib/pull/638.

**Pull request closed without merging**
